$schema: https://json.schemastore.org/eslintrc.json
root: true
env:
  es2021: true
  node: true
extends:
  - plugin:@typescript-eslint/strict-type-checked
  - plugin:@typescript-eslint/stylistic-type-checked
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.eslint.json
plugins:
  - "@typescript-eslint"
rules:
  "@typescript-eslint/consistent-type-imports":
    - "error"
    - fixStyle: separate-type-imports
  "@typescript-eslint/switch-exhaustiveness-check": "error"
