name: Docker CI

on:
  pull_request:
    branches:
      - main
  merge_group:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  docker:
    permissions:
      contents: read
      packages: write

    if: github.actor != 'nektos/act'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - if: github.actor != 'dependabot[bot]'
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - if: github.actor != 'dependabot[bot]'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            natoboram/gigachad.ts
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=tag
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=semver,pattern={{version}}

      - uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.ref_type == 'tag' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
